platform :ios, '9.0'

# 去掉烦人的警告
inhibit_all_warnings!

target 'GKPhotoBrowserDemo' do
  use_frameworks!
  
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'GKNavigationBarViewController'
  pod 'YYModel'
  pod 'GKCover'

end
