source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

# 去掉烦人的警告
inhibit_all_warnings!

target 'GKPhotoBrowserDemo' do
  use_frameworks!
  
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'YYWebImage', '~> 1.0.5'
  pod 'GKNavigationBarViewController'
  pod 'YYModel'
  pod 'GKCover'
  pod 'SDAutoLayout'
  pod 'SVProgressHUD'
  pod 'TZImagePickerController'

end
