platform :ios, '9.0'

target 'GKPhotoBrowserPod' do
  use_frameworks!

  pod 'AFNetworking'
  pod 'GKNavigationBarViewController'
  pod 'YYModel'
  pod 'GKCover'
  pod 'SDWebImage', '~> 5.0.0-beta6'
  pod 'SDAutoLayout'
  pod 'GKPhotoBrowser'

end
